### ISSUE TITLE
Error in tadm.py

### ISSUE THREAD

**Issue by LZleejean** [NVlabs/planercnn#16]
Traceback (most recent call last):
  File "/home/lz/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/home/lz/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/home/lz/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/home/lz/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/lz/anaconda3/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

I have this error when I evaluated the NYU dataset. Have you encountered this error? This seems to be a problem with the tqdm package, multithread. My tqdm is 4.28.1.

**Comment by art-programmer** [comment]
Sorry, I have not experienced such issues. Maybe you can try to remove the tqdm wrapper from the code. Just do something like, "for sample in dataloader:".
