### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__nms)

### ISSUE THREAD

**Issue by GuardianWang** [NVlabs/planercnn#22]
### Description 
When I run 

`python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images` 

to use the trained model, the following error was raised:

`ImportError: dynamic module does not define module export function (PyInit__nms)`

I googled such error and found that the dynamic module refers to those `.so` files. People with similar experience say that it is because the python versions used for compiling and importing are different. However, they are talking about using the `make` command, so I couldn't find a proper method to deal with the `nvcc` command.

 ### Some info:
`os` version: Ubuntu 14.04 LTS
`CUDA` version:  8.0.61
`gcc` version: 4.8.4
`python` version: 3.6
packages version: the same as `requirements.txt`

 ### The whole traceback info:
Traceback (most recent call last):
  File "evaluate.py", line 20, in <module>
    from models.model import *
  File "/home/ubuntu3/wzc/projects/planercnn/models/model.py", line 23, in <module>
    from nms.nms_wrapper import nms
  File "/home/ubuntu3/wzc/projects/planercnn/nms/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/home/ubuntu3/wzc/projects/planercnn/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/ubuntu3/wzc/projects/planercnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: dynamic module does not define module export function (PyInit__nms)

**Comment by GuardianWang** [comment]
Well, I tried another computer in my lab again and everything worked well...
My experience of debugging now is changing a computer, which can really save me a lot of time.
Now I just wonder what if, from the beginning, I could use the right computer to run the code? =_= Maybe this decision can save me 3 days to do other meaningful things lol.

### Configuration of this new computer
os Ubuntu 14.04.4
cuda 8.0.44
gcc 4.8.4
python 3.6

**Comment by GuardianWang** [comment]
The major difference between the 2 computers, I think, are GPU version. The first one in Titan and the second one is 1080.
