### ISSUE TITLE
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

### ISSUE THREAD

**Issue by unatsharma** [NVlabs/planercnn#41]
Hi,
I am getting the following error when I try to run evaluate.py:

`(planercnn) tanu.sharma@gnode45:~/planercnn/planercnn$ python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images
the number of images 3
  0%|                                                                                                          | 0/3 [00:00<?, ?it/s]specified_suffix: warping_refine
/home/tanu.sharma/planercnn/planercnn/models/model.py:1473: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
rm: cannot remove 'test/inference/*_final.png': No such file or directory
Traceback (most recent call last):
  File "evaluate.py", line 664, in <module>
    evaluate(args)
  File "evaluate.py", line 575, in evaluate
    detection_pair = detector.detect(sample)
  File "evaluate.py", line 96, in detect
    rpn_class_logits, rpn_pred_bbox, target_class_ids, mrcnn_class_logits, target_deltas, mrcnn_bbox, target_mask, mrcnn_mask, target_parameters, mrcnn_parameters, detections, detection_masks, detection_gt_parameters, detection_gt_masks, rpn_rois, roi_features, roi_indices, depth_np_pred = self.model.predict([images, image_metas, gt_class_ids, gt_boxes, gt_masks, gt_parameters, camera], mode='inference_detection', use_nms=2, use_refinement=True)
  File "/home/tanu.sharma/planercnn/planercnn/models/model.py", line 1658, in predict
    [p2_out, p3_out, p4_out, p5_out, p6_out] = self.fpn(molded_images)
  File "/home/tanu.sharma/miniconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanu.sharma/planercnn/planercnn/models/model.py", line 121, in forward
    x = self.C1(x)
  File "/home/tanu.sharma/miniconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanu.sharma/miniconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/tanu.sharma/miniconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanu.sharma/miniconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS
`

My anaconda environment is :
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py37_0  
cffi                      1.11.5                   pypi_0    pypi
cloudpickle               1.4.0                    pypi_0    pypi
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.6.5                 cuda9.0_0  
cycler                    0.10.0                   pypi_0    pypi
dask                      2.15.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
intel-openmp              2019.4                      243  
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
matplotlib                3.2.1                    pypi_0    pypi
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py37h7dd41cf_0  
mkl_random                1.0.1            py37h4414c95_1  
nccl                      1.3.5                 cuda9.0_0  
ncurses                   6.2                  he6710b0_0  
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.15.4           py37h1d66e8a_0  
numpy-base                1.15.4           py37h81de0dd_0  
opencv-python             3.4.4.19                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.1.2                    pypi_0    pypi
pip                       20.0.2                   py37_1  
pycparser                 2.20                       py_0  
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.7           hcf32534_0_cpython  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   0.4.1            py37ha74772b_0  
pywavelets                1.1.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
scikit-image              0.14.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.1.3                   py37_0  
six                       1.14.0                   pypi_0    pypi
sqlite                    3.31.1               h62c20be_1  
tbb                       2020.0               hfd86e86_0  
tbb4py                    2020.0           py37hfd86e86_0  
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                   pypi_0    pypi
tqdm                      4.28.1                   pypi_0    pypi
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

Why is this error coming? I tried searching and found [https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-success/28045](url). But it is not helping.

Please tell how to resolve this.

**Comment by unatsharma** [comment]
I was able to resolve the issue by installing cuda90 using 
`conda install pytorch=0.4.1 cuda90 -c pytorch `.
