### ISSUE TITLE
Problem about parse.py

### ISSUE THREAD

**Issue by mei123hao** [NVlabs/planercnn#48]
I try to run parse.py to get the training data. However, it seems that the parse.py scripts cannot run sucessfully! I try to modify  it and run. But now it always show following errors:

Traceback (most recent call last):
  File "/home/viets/worksapce/planercnn/data_prep/parse.py", line 791, in <module>
    readMesh(scene_id)
  File "/home/viets/worksapce/planercnn/data_prep/parse.py", line 750, in readMesh
    colors = colorMap[planeSegmentation]    
IndexError: index 15688 is out of bounds for axis 0 with size 207

It seems that the variable planeSegmentation's length is too long, the colorMap 's length is 207. But I cannot figure out how to fix this bug! Can anyone help me ! Thanks!!

**Comment by mei123hao** [comment]
i have solved the problem through creating a python2 conda enviroment..

**Comment by Haoran-001** [comment]
@mei123hao Excuse me, I want to ask a question about the program parse.py: when I run parse.py, and it has an error " NameError: global name 'fitPlane' is not defined". And  I really don't see the definition of "fitplane" in the py file. Do you have the same problem? Really thank you.

**Comment by Karthikaddagadderamesh** [comment]
@Haoran-001  did you solve this?

**Comment by lxraptx** [comment]
> @Haoran-001 did you solve this?

utils.py appears to contain fitPlane()
