### ISSUE TITLE
No module named 'nms._ext.nms._nms

### ISSUE THREAD

**Issue by Suujy** [NVlabs/planercnn#5]
I've already created a conda env following **Getting Started**. However, I still got this error and don't know how to fix it.

Traceback (most recent call last):
  File "/home/sujunyu/planercnn-master/train_planercnn.py", line 17, in <module>
    from models.model import *
  File "/home/sujunyu/planercnn-master/models/model.py", line 23, in <module>
    from nms.nms_wrapper import nms
  File "/home/sujunyu/planercnn-master/nms/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/home/sujunyu/planercnn-master/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/sujunyu/planercnn-master/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'nms._ext.nms._nms'

**Update:**
    After compiling nms and roialign, and using planercnn env's bin/python, still got the error. Looks like although I've used env's python but the programme still fetch me default cuda, which version is 10.1. 

File "/home/sujunyu/planercnn-master/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/sujunyu/planercnn-master/nms/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd

**Comment by art-programmer** [comment]
Sorry for the late response. It seems that Cuda 10 doesn't work. And which python version are you using?

**Comment by Suujy** [comment]
Yes and I have solve it by using docker. And may I ask if the whole ScanNet should be download？ Cause it's 1.2T and is consuming tons of time.




------------------ 原始邮件 ------------------
发件人: "art-programmer"<notifications@github.com>;
发送时间: 2019年6月15日(星期六) 晚上10:52
收件人: "NVlabs/planercnn"<planercnn@noreply.github.com>;
抄送: "JerrySu"<401839797@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NVlabs/planercnn] No module named 'nms._ext.nms._nms (#5)




Sorry for the late response. It seems that Cuda 10 doesn't work. And which python version are you using?

**Comment by tyluann** [comment]
i am running into the same error:
Traceback (most recent call last):
  File "evaluate.py", line 20, in <module>
    from models.model import *
  File "/data4/tyluan/Workspace/py_projects/planercnn/models/model.py", line 23, in <module>
    from nms.nms_wrapper import nms
  File "/data4/tyluan/Workspace/py_projects/planercnn/nms/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/data4/tyluan/Workspace/py_projects/planercnn/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/data4/tyluan/Workspace/py_projects/planercnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /data4/tyluan/Workspace/py_projects/planercnn/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

Have you found a solution yet?

My cuda version is 10.0.130

**Comment by AdriDev101** [comment]
Hello to you all!
I have more or less the same output as @tyluann reported.

```
Traceback (most recent call last):
  File "evaluate.py", line 20, in <module>
    from models.model import *
  File "/home/adrian/RedesNeuronales/planercnn/models/model.py", line 23, in <module>
    from nms.nms_wrapper import nms
  File "/home/adrian/RedesNeuronales/planercnn/nms/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/home/adrian/RedesNeuronales/planercnn/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/adrian/RedesNeuronales/planercnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/adrian/RedesNeuronales/planercnn/nms/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd
```


Has it been solved yet?
My cuda version is V10.1.243

**Comment by rohitdhote111** [comment]
I am facing the the same issue but cuda version is 12

(planercnn) rohith@AADT035:~/workspace/planercnn$ nvidia-smi
Fri Jun 21 13:07:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti     Off | 00000000:01:00.0 Off |                  N/A |
|  0%   49C    P8              22W / 350W |      1MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
(planercnn) rohith@AADT035:/workspace/planercnn$ python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images
Traceback (most recent call last):
  File "evaluate.py", line 20, in <module>
    from models.model import *
  File "/home/rohith/workspace/planercnn/models/model.py", line 23, in <module>
    from nms.nms_wrapper import nms
  File "/home/rohith/workspace/planercnn/nms/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/home/rohith/workspace/planercnn/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/rohith/workspace/planercnn/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'nms._ext.nms._nms'
(planercnn) rohith@AADT035:~/workspace/planercnn$
