### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Tarekbouamer** [NVlabs/planercnn#7]
Hello; 
I m trying to run planercnn inference with warping and refine checkpoint However I get cuda error: out of memory as bellow: 

(planercnn) tarek@tarek:~/planercnn$ python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images
the number of images 3
  0%|                                                                                                                                                                                 | 0/3 [00:00<?, ?it/s]/home/tarek/planercnn/models/model.py:1473: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
rm: cannot remove 'test/inference/*_final.png': No such file or directory
/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f80d99de6a8>
Traceback (most recent call last):
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/multiprocessing/reduction.py", line 153, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "evaluate.py", line 660, in <module>
    evaluate(args)
  File "evaluate.py", line 571, in evaluate
    detection_pair = detector.detect(sample)
  File "evaluate.py", line 147, in detect
    results = self.refine_model(image, image_2, camera, masks_inp, detection_dict['detection'][:, 6:9], plane_depth, depth_np)
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tarek/planercnn/models/refinement_net.py", line 658, in forward
    result = self.refinement_net(image_1, camera, result)
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tarek/planercnn/models/refinement_net.py", line 482, in forward
    masks, depth, plane = self.refinement_block(image_1.repeat((len(masks), 1, 1, 1)), prev_predictions, prev_result['plane'])
  File "/home/tarek/anaconda3/envs/planercnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tarek/planercnn/models/refinement_net.py", line 93, in forward
    y_0 = self.pred(torch.cat([y_1, x_0], dim=1))
**RuntimeError: CUDA error: out of memory**
..........................................................................................................
I m using Cuda 9.0 with gcc 6
python 3.7 and pytorch 0.4.1
.........................................................................................................
Can You please check the checkpoint file for Refine +Warping provided in your Drive

Thanks
Tarek

**Comment by mysunnyday** [comment]
I meet the same out of memory problem , what's your solution ?

**Comment by mysunnyday** [comment]
do you know the minimum memory requirement of the provided model ? thx:)

**Comment by cgarg-tud** [comment]
how did you resolve this problem @mysunnyday

**Comment by ajithvcoder** [comment]
@mysunnyday was there any solution
